### ISSUE TITLE
Review branding of the CHT Technical Radars

### ISSUE THREAD

**Issue by andrablaj** [medic/cht-tech-radar-contributors#2]
Review branding of CHT Technical Radars (this applies to both `Contributors` and `Implementers`) to match Medic/CHT style.
Areas to consider:

- fonts
- colors
- logo

**Comment by andrablaj** [comment]
@n-orlowski for the [Technical Radars](https://docs.communityhealthtoolkit.org/cht-tech-radar-contributors/index.html) I used the styles from [this rebranding document](https://docs.google.com/presentation/d/13-nevXMFM5FzFGDW7H0-n27-0EGr997yvUlEo6HoTXs/edit#slide=id.gce178f452d_0_0). 
Can you review the style on the radar and guide me to the correct styles if these are not up to date?
Also, do you have a list of fonts we should use for CHT/Medic documentation and the latest CHT logos? 
Thank you ✨

**Comment by ghost** [comment]
@andrablaj the radars look great and are well aligned with the rebrand 😄 ✨ 

More info can be found [here](https://www.notion.so/medicmobile/Our-Evolved-Brand-df7be28dae1e48e482761d075248ab00?pvs=4#ed43fd07318f4ad38cdef9f35918942d) on fonts (headlines are usually bold and use Spartan, body text being Noto seems aligned)

Latest CHT logos are [here](https://drive.google.com/drive/u/1/folders/1VVLm9WbuNNFwpg0bf7qLa3uEcE3uDbRd)

A few thoughts on the use of color are that I find it a bit confusing when reading these labels 
<img width="675" alt="Screen Shot 2023-09-21 at 1 07 28 PM" src="https://github.com/medic/cht-tech-radar-contributors/assets/59581790/43be2596-2d9b-426d-96b8-637706c80539">

because they are reused in the radar graphic and it makes me think there is a correlation between "Quadrant 1" and "Stop", "Quadrant 2" and "Assess", and "Quadrant 3" and "Trial".

It might make more sense to use more neutral colors for the quadrants, ex.
<img width="120" alt="Screen Shot 2023-09-21 at 1 15 28 PM" src="https://github.com/medic/cht-tech-radar-contributors/assets/59581790/828fe466-26fa-40cd-8ff5-0d6d469132a3">
from the brand document you shared and then appropriate status colors for the labels, ex. green for Adopt, yellow for Trial, the darker orange for Stop etc. 

Hope this is helpful and LMK if you need anything else!

**Comment by andrablaj** [comment]
Thank you @n-orlowski, this is very helpful. 💯 

I followed your instructions, updated the colors, and added the logo. I am looking into updating the titles to Spartan. 

Please review the updated color scheme [here](https://docs.communityhealthtoolkit.org/cht-tech-radar-contributors/index.html) and let me know if you have further feedback. Thank you!

**Comment by ghost** [comment]
LGTM! 🎉
